### ISSUE TITLE
Build and install instructions

### ISSUE THREAD

**Issue by cpetry** [mariotaku/moonlight-webos#1]
Hi there,

could you please add some build and install instructions? This seems to be exactly what I'm looking for.

Thanks!

**Comment by mariotaku** [comment]
Thank you for being interested in this project. I've cleaned up code and updated build instructions. You can find it here: https://github.com/mariotaku/moonlight-webos/blob/main/README.md

Please note this project is in very early stage development. Settings are not implemented and UI is undone. Also the performance is not ideal as there's no hardware acceleration.
But nevertheless let's have hope as I'm still working hard on reverse engineering to find out proper way to render video.
